<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <Optimize>True</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <Optimize>False</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Envitia.MapLink.DDO64d">
      <HintPath>..\..\MapLink\bin64\Envitia.MapLink.DDO64d.dll</HintPath>
      <Private></Private>
    </Reference>
    <Reference Include="Envitia.MapLink.NativeHelpers">
      <HintPath>..\..\MapLink\bin64\Envitia.MapLink.NativeHelpers.dll</HintPath>
      <Private></Private>
    </Reference>
    <Reference Include="Envitia.MapLink.TrackManager64">
      <HintPath>..\..\MapLink\bin64\Envitia.MapLink.TrackManager64.dll</HintPath>
      <Private></Private>
    </Reference>
    <Reference Include="Envitia.MapLink.TSLNSkiaDrawingSurfaceWPFControl">
      <HintPath>..\..\MapLink\bin64\Envitia.MapLink.TSLNSkiaDrawingSurfaceWPFControl.dll</HintPath>
      <Private></Private>
    </Reference>
    <Reference Include="Envitia.MapLink64">
      <HintPath>..\..\MapLink\bin64\Envitia.MapLink64.dll</HintPath>
      <Private></Private>
    </Reference>
  </ItemGroup>

</Project>
