using System;

namespace MovingFeaturesSample.MapLayers
{
  /// <summary>
  /// A map layer that visualises a map generated by MapLink Studio.
  /// </summary>
  public class MapLinkMapLayer : MapLayer
  {
    private Envitia.MapLink.TSLNDataLayer DataLayer { get; set; }

    public override void ConfigureMapLayer(Envitia.MapLink.TSLN2DDrawingSurface surface, bool visible)
    {
      surface.setDataLayerProps(Identifier(), Envitia.MapLink.TSLNPropertyEnum.TSLNPropertyVisible, visible ? 1 : 0);
      surface.setDataLayerProps(Identifier(), Envitia.MapLink.TSLNPropertyEnum.TSLNPropertyDetect, visible ? 1 : 0);

      surface.setDataLayerProps(Identifier(), Envitia.MapLink.TSLNPropertyEnum.TSLNPropertyTransparency, IsFoundationLayer ? 255: Opacity);

      if (DataLayer != null)
      {
        DataLayer.notifyChanged();
      }
    }

    public override Envitia.MapLink.TSLNDataLayer GetDataLayer()
    {
      if (DataLayer != null)
        return DataLayer;

      string errors = "";

      DataLocation = DataLocation.Replace("%CD%", System.AppDomain.CurrentDomain.BaseDirectory);

      DataLayer = new Envitia.MapLink.TSLNMapDataLayer();
      if (!DataLayer.loadData(DataLocation))
      {
        DataLayer = null;
        string error = Envitia.MapLink.TSLNErrorStack.errorString("\nErrors:\n");
        errors += "Failed to load data: " + Property + error + "\n";
      }

      if (errors.Length > 0)
      {
        System.Windows.MessageBox.Show(errors);
      }

      return DataLayer;
    }
  }
}
